[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
c_spl_wrapper = "D3FaNQVD8NZC6CFT1AS8Rq2G26iAGZ19CgLJXNMfGAjY"

[programs.devnet]
c_spl_wrapper = "D3FaNQVD8NZC6CFT1AS8Rq2G26iAGZ19CgLJXNMfGAjY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "http://127.0.0.1:8899"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[[test.validator.account]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
filename = "target/deploy/spl_token_2022.so"

[hooks]

